# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pixlet < Formula
  desc "App runtime and UX toolkit for pixel-based apps."
  homepage "https://github.com/tidbyt/pixlet"
  version "0.27.3"

  depends_on "webp"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tidbyt/pixlet/releases/download/v0.27.3/pixlet_0.27.3_darwin_arm64.tar.gz"
      sha256 "34c9493ac8173abfc0fbc8db64575847d6539206a6706e7925066c3bb13f38a6"

      def install
        bin.install "pixlet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tidbyt/pixlet/releases/download/v0.27.3/pixlet_0.27.3_darwin_amd64.tar.gz"
      sha256 "052cf17b6aa9992963e6c2e80772d513ab3dee44597eb6375f3c6c67735cb8d9"

      def install
        bin.install "pixlet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tidbyt/pixlet/releases/download/v0.27.3/pixlet_0.27.3_linux_amd64.tar.gz"
      sha256 "a648f07c5d10f272ddaca036bab4529b912402bfef89fb7aaeaea9a1f45f1749"

      def install
        bin.install "pixlet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tidbyt/pixlet/releases/download/v0.27.3/pixlet_0.27.3_linux_arm64.tar.gz"
      sha256 "7fc049b4f434721a23624f9def95196d798c103d331f59d5c6d0026478231a2c"

      def install
        bin.install "pixlet"
      end
    end
  end

  test do
    system "#{bin}/pixlet --version"
  end
end
