# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pixlet < Formula
  desc "App runtime and UX toolkit for pixel-based apps."
  homepage "https://github.com/tidbyt/pixlet"
  version "0.24.3"

  depends_on "webp"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tidbyt/pixlet/releases/download/v0.24.3/pixlet_0.24.3_darwin_arm64.tar.gz"
      sha256 "955fbd2fec27097345a8a45de9dde481fad17fe6701e1d2a12eb1ab95de8b890"

      def install
        bin.install "pixlet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tidbyt/pixlet/releases/download/v0.24.3/pixlet_0.24.3_darwin_amd64.tar.gz"
      sha256 "fde0888743f943cbbfd0a77099ade4106a7d71e6d3de4334152127a7666bb606"

      def install
        bin.install "pixlet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tidbyt/pixlet/releases/download/v0.24.3/pixlet_0.24.3_linux_amd64.tar.gz"
      sha256 "ba7c83ac299ecaf7fb6dc36a501f363a7cd1ea3155de23ca0efea5eb32b65130"

      def install
        bin.install "pixlet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tidbyt/pixlet/releases/download/v0.24.3/pixlet_0.24.3_linux_arm64.tar.gz"
      sha256 "1058e8dcd6c3832e9031203b43d755740ff408ebd4e791ce51f9a061a5087411"

      def install
        bin.install "pixlet"
      end
    end
  end

  test do
    system "#{bin}/pixlet --version"
  end
end
