# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pixlet < Formula
  desc "App runtime and UX toolkit for pixel-based apps."
  homepage "https://github.com/tidbyt/pixlet"
  version "0.32.4"

  depends_on "webp"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tidbyt/pixlet/releases/download/v0.32.4/pixlet_0.32.4_darwin_arm64.tar.gz"
      sha256 "53fcfa049fd635d3a93bb5f16012c0116254982609126c69d32d05ad37e044be"

      def install
        bin.install "pixlet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tidbyt/pixlet/releases/download/v0.32.4/pixlet_0.32.4_darwin_amd64.tar.gz"
      sha256 "f295fcab38391c82a06f84ed20bbf3d91de6e2477fed6c3142c506f5013fca8b"

      def install
        bin.install "pixlet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tidbyt/pixlet/releases/download/v0.32.4/pixlet_0.32.4_linux_amd64.tar.gz"
      sha256 "3c4d9ae6c1e8cc6b8524d873202bb4567d8d2e6f4e115b7bd3ed51e1744ddbae"

      def install
        bin.install "pixlet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tidbyt/pixlet/releases/download/v0.32.4/pixlet_0.32.4_linux_arm64.tar.gz"
      sha256 "75fb958c8360be4609296c7b6cf20c80d63544859e031d98976ce328d73529cf"

      def install
        bin.install "pixlet"
      end
    end
  end

  test do
    system "#{bin}/pixlet --version"
  end
end
